// mockData.ts — Full TideLift demo seed data
// 5 suppliers, 8 surplus lots, 3 canning facilities, 6 food banks, 12 quotes

import type {
  Supplier, SurplusLot, CanningFacility, FoodBank, Quote, Approval, Shipment, AuditEvent
} from './types';

// ── Suppliers ─────────────────────────────────────────────────────────────────
export const SUPPLIERS: Supplier[] = [
  {
    id: 'sup-001',
    name: 'Monterey Bay Fisheries',
    contactName: 'Rosa Gutierrez',
    contactEmail: 'rosa@montereybay.fish',
    contactPhone: '831-555-0101',
    location: 'Monterey, CA',
    port: 'Monterey Harbor',
    species: ['Albacore Tuna', 'Pacific Salmon', 'Pacific Sardine'],
    certifications: ['MSC', 'HACCP'],
    avgMonthlyLbs: 45000,
    taxExemptEligible: true,
  },
  {
    id: 'sup-002',
    name: 'San Diego Tuna Fleet',
    contactName: 'Miguel Reyes',
    contactEmail: 'miguel@sdtunafleet.com',
    contactPhone: '619-555-0202',
    location: 'San Diego, CA',
    port: 'Tuna Harbor',
    species: ['Albacore Tuna', 'Pacific Sardine'],
    certifications: ['HACCP', 'SQF'],
    avgMonthlyLbs: 62000,
    taxExemptEligible: true,
  },
  {
    id: 'sup-003',
    name: 'Bodega Bay Crab Co.',
    contactName: 'Lena Park',
    contactEmail: 'lena@bodegacrab.com',
    contactPhone: '707-555-0303',
    location: 'Bodega Bay, CA',
    port: 'Bodega Bay Harbor',
    species: ['Dungeness Crab'],
    certifications: ['MSC', 'HACCP'],
    avgMonthlyLbs: 12000,
    taxExemptEligible: false,
  },
  {
    id: 'sup-004',
    name: 'Eureka Pacific Seafood',
    contactName: 'James Thornton',
    contactEmail: 'james@eurekapacific.com',
    contactPhone: '707-555-0404',
    location: 'Eureka, CA',
    port: 'Humboldt Bay',
    species: ['Pacific Salmon', 'Pacific Halibut'],
    certifications: ['MSC', 'HACCP', 'BAP'],
    avgMonthlyLbs: 28000,
    taxExemptEligible: true,
  },
  {
    id: 'sup-005',
    name: 'Half Moon Bay Seafarm',
    contactName: 'Diane Chen',
    contactEmail: 'diane@hmbayfarm.com',
    contactPhone: '650-555-0505',
    location: 'Half Moon Bay, CA',
    port: 'Pillar Point Harbor',
    species: ['Pacific Halibut', 'Pacific Sardine', 'Pacific Salmon'],
    certifications: ['MSC', 'HACCP'],
    avgMonthlyLbs: 18000,
    taxExemptEligible: true,
  },
];

// ── Surplus Lots ──────────────────────────────────────────────────────────────
export const SURPLUS_LOTS: SurplusLot[] = [
  {
    id: 'lot-001',
    supplierId: 'sup-001',
    species: 'Albacore Tuna',
    weightLbs: 4200,
    harvestDate: '2026-07-14',
    expiryDate: '2026-07-21',
    marketPricePerLb: 1.85,
    proposedDiscountPct: 22,
    minOrderLbs: 500,
    status: 'AVAILABLE',
    notes: 'Grade A, ice-packed, available at dock.',
  },
  {
    id: 'lot-002',
    supplierId: 'sup-002',
    species: 'Pacific Sardine',
    weightLbs: 8900,
    harvestDate: '2026-07-13',
    expiryDate: '2026-07-20',
    marketPricePerLb: 0.65,
    proposedDiscountPct: 30,
    minOrderLbs: 1000,
    status: 'AVAILABLE',
    notes: 'Large school catch, must move within 7 days.',
  },
  {
    id: 'lot-003',
    supplierId: 'sup-003',
    species: 'Dungeness Crab',
    weightLbs: 1100,
    harvestDate: '2026-07-15',
    expiryDate: '2026-07-19',
    marketPricePerLb: 3.20,
    proposedDiscountPct: 40,
    minOrderLbs: 200,
    status: 'AVAILABLE',
    notes: 'Broken/whole mix from processing line — ideal for canning.',
  },
  {
    id: 'lot-004',
    supplierId: 'sup-004',
    species: 'Pacific Salmon',
    weightLbs: 3600,
    harvestDate: '2026-07-12',
    expiryDate: '2026-07-22',
    marketPricePerLb: 2.40,
    proposedDiscountPct: 18,
    minOrderLbs: 400,
    status: 'PENDING_PROCUREMENT',
    notes: 'King salmon trim from smoking operation.',
  },
  {
    id: 'lot-005',
    supplierId: 'sup-004',
    species: 'Pacific Halibut',
    weightLbs: 2200,
    harvestDate: '2026-07-10',
    expiryDate: '2026-07-24',
    marketPricePerLb: 4.10,
    proposedDiscountPct: 25,
    minOrderLbs: 300,
    status: 'AVAILABLE',
  },
  {
    id: 'lot-006',
    supplierId: 'sup-005',
    species: 'Pacific Sardine',
    weightLbs: 6500,
    harvestDate: '2026-07-14',
    expiryDate: '2026-07-21',
    marketPricePerLb: 0.70,
    proposedDiscountPct: 28,
    minOrderLbs: 800,
    status: 'AVAILABLE',
  },
  {
    id: 'lot-007',
    supplierId: 'sup-001',
    species: 'Pacific Salmon',
    weightLbs: 5100,
    harvestDate: '2026-07-08',
    expiryDate: '2026-07-18',
    marketPricePerLb: 2.30,
    proposedDiscountPct: 35,
    minOrderLbs: 600,
    status: 'PROCUREMENT_CONFIRMED',
    notes: 'Sockeye, high urgency — 3 days to expiry.',
  },
  {
    id: 'lot-008',
    supplierId: 'sup-005',
    species: 'Pacific Halibut',
    weightLbs: 1800,
    harvestDate: '2026-07-11',
    expiryDate: '2026-07-25',
    marketPricePerLb: 4.00,
    proposedDiscountPct: 20,
    minOrderLbs: 250,
    status: 'AVAILABLE',
  },
];

// ── Canning Facilities ────────────────────────────────────────────────────────
export const CANNING_FACILITIES: CanningFacility[] = [
  {
    id: 'fac-001',
    name: 'Bay Area Cannery Co-Pack',
    location: 'Richmond, CA',
    state: 'CA',
    capacityLbsPerDay: 5000,
    costPerCan: 0.38,
    compatibleSpecies: ['Albacore Tuna', 'Pacific Sardine', 'Pacific Salmon', 'Pacific Halibut'],
    certifications: ['FDA', 'HACCP', 'SQF Level 2'],
    availableSlots: [
      { date: '2026-07-18', capacityLbs: 4000, reserved: false },
      { date: '2026-07-19', capacityLbs: 5000, reserved: false },
      { date: '2026-07-22', capacityLbs: 5000, reserved: false },
    ],
  },
  {
    id: 'fac-002',
    name: 'Central Coast Cannery',
    location: 'Salinas, CA',
    state: 'CA',
    capacityLbsPerDay: 3000,
    costPerCan: 0.42,
    compatibleSpecies: ['Pacific Sardine', 'Albacore Tuna', 'Pacific Salmon'],
    certifications: ['FDA', 'HACCP'],
    availableSlots: [
      { date: '2026-07-19', capacityLbs: 3000, reserved: false },
      { date: '2026-07-20', capacityLbs: 2500, reserved: false },
      { date: '2026-07-23', capacityLbs: 3000, reserved: false },
    ],
  },
  {
    id: 'fac-003',
    name: 'NorCal Seafood Processing',
    location: 'Eureka, CA',
    state: 'CA',
    capacityLbsPerDay: 7000,
    costPerCan: 0.35,
    compatibleSpecies: ['Pacific Salmon', 'Pacific Halibut', 'Dungeness Crab', 'Albacore Tuna'],
    certifications: ['FDA', 'HACCP', 'MSC Chain-of-Custody', 'SQF Level 3'],
    availableSlots: [
      { date: '2026-07-17', capacityLbs: 7000, reserved: false },
      { date: '2026-07-18', capacityLbs: 6000, reserved: false },
      { date: '2026-07-21', capacityLbs: 7000, reserved: false },
    ],
  },
];

// ── Food Banks ────────────────────────────────────────────────────────────────
export const FOOD_BANKS: FoodBank[] = [
  {
    id: 'fb-001',
    name: 'Alameda County Community Food Bank',
    contactName: 'Marcus Williams',
    contactEmail: 'marcus@accfb.org',
    location: 'Oakland, CA',
    region: 'East Bay',
    monthlyDemandCases: 320,
    dietaryRestrictions: ['halal', 'low-sodium'],
    accessWindows: ['Mon 9-12', 'Wed 9-12', 'Fri 9-12'],
    priorityScore: 92,
  },
  {
    id: 'fb-002',
    name: 'Fruitvale Community Pantry',
    contactName: 'Sofia Ramirez',
    contactEmail: 'sofia@fruitvalepantry.org',
    location: 'Oakland, CA',
    region: 'East Bay',
    monthlyDemandCases: 180,
    dietaryRestrictions: ['no-shellfish'],
    accessWindows: ['Tue 10-14', 'Thu 10-14'],
    priorityScore: 85,
  },
  {
    id: 'fb-003',
    name: 'Second Harvest of Silicon Valley',
    contactName: 'Priya Nair',
    contactEmail: 'priya@shfb.org',
    location: 'San Jose, CA',
    region: 'South Bay',
    monthlyDemandCases: 540,
    dietaryRestrictions: [],
    accessWindows: ['Mon 8-16', 'Wed 8-16', 'Fri 8-16'],
    priorityScore: 78,
  },
  {
    id: 'fb-004',
    name: 'SF-Marin Food Bank',
    contactName: 'David Okafor',
    contactEmail: 'david@sfmfoodbank.org',
    location: 'San Francisco, CA',
    region: 'Bay Area North',
    monthlyDemandCases: 410,
    dietaryRestrictions: ['kosher-friendly'],
    accessWindows: ['Tue 9-13', 'Thu 9-13', 'Sat 9-13'],
    priorityScore: 88,
  },
  {
    id: 'fb-005',
    name: 'Redwood Empire Food Bank',
    contactName: 'Janet Hill',
    contactEmail: 'janet@refb.org',
    location: 'Santa Rosa, CA',
    region: 'North Bay',
    monthlyDemandCases: 230,
    dietaryRestrictions: [],
    accessWindows: ['Mon 10-14', 'Thu 10-14'],
    priorityScore: 74,
  },
  {
    id: 'fb-006',
    name: 'Salinas Valley Food Bank',
    contactName: 'Ernesto Vega',
    contactEmail: 'ernesto@svfb.org',
    location: 'Salinas, CA',
    region: 'Central Coast',
    monthlyDemandCases: 290,
    dietaryRestrictions: ['low-sodium'],
    accessWindows: ['Wed 8-12', 'Fri 8-12'],
    priorityScore: 81,
  },
];

// ── Quotes ────────────────────────────────────────────────────────────────────
export const QUOTES: Quote[] = [
  { id: 'q-001', lotId: 'lot-001', supplierId: 'sup-001', pricePerLb: 1.44, minOrderLbs: 500, validUntil: '2026-07-21', notes: 'Counter at 22% off. Bulk non-profit rate.', status: 'OPEN' },
  { id: 'q-002', lotId: 'lot-001', supplierId: 'sup-001', pricePerLb: 1.52, minOrderLbs: 1000, validUntil: '2026-07-21', notes: 'Initial offer.', status: 'OPEN' },
  { id: 'q-003', lotId: 'lot-002', supplierId: 'sup-002', pricePerLb: 0.46, minOrderLbs: 1000, validUntil: '2026-07-20', notes: 'Best price for full lot purchase.', status: 'OPEN' },
  { id: 'q-004', lotId: 'lot-002', supplierId: 'sup-002', pricePerLb: 0.50, minOrderLbs: 2000, validUntil: '2026-07-20', notes: 'Split lot accepted.', status: 'OPEN' },
  { id: 'q-005', lotId: 'lot-003', supplierId: 'sup-003', pricePerLb: 1.92, minOrderLbs: 200, validUntil: '2026-07-19', notes: '40% off — crab pieces only. Urgent.', status: 'OPEN' },
  { id: 'q-006', lotId: 'lot-004', supplierId: 'sup-004', pricePerLb: 1.97, minOrderLbs: 400, validUntil: '2026-07-22', notes: 'Accepted — procurement in progress.', status: 'ACCEPTED' },
  { id: 'q-007', lotId: 'lot-005', supplierId: 'sup-004', pricePerLb: 3.08, minOrderLbs: 300, validUntil: '2026-07-24', notes: '25% off halibut. Premium species.', status: 'OPEN' },
  { id: 'q-008', lotId: 'lot-006', supplierId: 'sup-005', pricePerLb: 0.50, minOrderLbs: 800, validUntil: '2026-07-21', notes: 'Large sardine volume — cooperative pricing.', status: 'OPEN' },
  { id: 'q-009', lotId: 'lot-007', supplierId: 'sup-001', pricePerLb: 1.50, minOrderLbs: 600, validUntil: '2026-07-18', notes: 'Confirmed — sockeye salmon. Urgent pickup.', status: 'ACCEPTED' },
  { id: 'q-010', lotId: 'lot-008', supplierId: 'sup-005', pricePerLb: 3.20, minOrderLbs: 250, validUntil: '2026-07-25', notes: '20% off halibut trim.', status: 'OPEN' },
  { id: 'q-011', lotId: 'lot-001', supplierId: 'sup-001', pricePerLb: 1.40, minOrderLbs: 4200, validUntil: '2026-07-21', notes: 'Full lot price. Best rate available.', status: 'OPEN' },
  { id: 'q-012', lotId: 'lot-005', supplierId: 'sup-004', pricePerLb: 3.20, minOrderLbs: 1000, validUntil: '2026-07-24', notes: 'Volume discount on full lot.', status: 'OPEN' },
];

// ── Approvals ─────────────────────────────────────────────────────────────────
export const APPROVALS: Approval[] = [
  {
    id: 'apr-001',
    approvalType: 'PROCUREMENT',
    entityId: 'lot-004',
    entityType: 'SurplusLot',
    status: 'APPROVED',
    operatorId: 'operator-ken',
    rationale: 'Strong discount (18%), high-demand species (salmon), facility capacity confirmed at fac-003.',
    notes: 'Approved — price meets food bank budget threshold.',
    createdAt: '2026-07-13T10:00:00Z',
    resolvedAt: '2026-07-13T11:22:00Z',
  },
  {
    id: 'apr-002',
    approvalType: 'FACILITY_BOOKING',
    entityId: 'lot-004',
    entityType: 'SurplusLot',
    status: 'APPROVED',
    operatorId: 'operator-ken',
    rationale: 'NorCal Seafood Processing (fac-003) best match: species-compatible, highest capacity, lowest cost/can ($0.35).',
    createdAt: '2026-07-13T11:30:00Z',
    resolvedAt: '2026-07-13T12:05:00Z',
  },
  {
    id: 'apr-003',
    approvalType: 'PROCUREMENT',
    entityId: 'lot-007',
    entityType: 'SurplusLot',
    status: 'APPROVED',
    operatorId: 'operator-ken',
    rationale: 'Emergency approval — lot expires 2026-07-18. 35% discount ($1.50/lb). Highest score lot in pipeline.',
    notes: 'Rush approved. Coordinate same-day pickup.',
    createdAt: '2026-07-14T08:00:00Z',
    resolvedAt: '2026-07-14T08:15:00Z',
  },
];

// ── Shipments ─────────────────────────────────────────────────────────────────
export const SHIPMENTS: Shipment[] = [
  {
    id: 'shp-001',
    lotId: 'lot-004',
    facilityId: 'fac-003',
    foodBankId: 'fb-001',
    cansProduced: 5702,
    weightLbs: 3600,
    status: 'IN_TRANSIT',
    estimatedPickup: '2026-07-17',
    estimatedArrival: '2026-07-23',
  },
  {
    id: 'shp-002',
    lotId: 'lot-007',
    facilityId: 'fac-001',
    foodBankId: 'fb-003',
    cansProduced: 8078,
    weightLbs: 5100,
    status: 'CONFIRMED',
    estimatedPickup: '2026-07-16',
    estimatedArrival: '2026-07-22',
  },
];

// ── Audit Events ──────────────────────────────────────────────────────────────
export const AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'aud-001',
    entityType: 'SurplusLot',
    entityId: 'lot-004',
    action: 'STATUS_CHANGED',
    actor: 'agent:scorer',
    beforeState: { status: 'AVAILABLE' },
    afterState: { status: 'SCORING', score: 72 },
    timestamp: '2026-07-13T09:50:00Z',
  },
  {
    id: 'aud-002',
    entityType: 'Approval',
    entityId: 'apr-001',
    action: 'APPROVAL_CREATED',
    actor: 'agent:procure',
    afterState: { approvalType: 'PROCUREMENT', status: 'PENDING' },
    timestamp: '2026-07-13T10:00:00Z',
  },
  {
    id: 'aud-003',
    entityType: 'Approval',
    entityId: 'apr-001',
    action: 'APPROVAL_RESOLVED',
    actor: 'operator-ken',
    beforeState: { status: 'PENDING' },
    afterState: { status: 'APPROVED', notes: 'Price meets threshold' },
    timestamp: '2026-07-13T11:22:00Z',
  },
  {
    id: 'aud-004',
    entityType: 'SurplusLot',
    entityId: 'lot-004',
    action: 'STATUS_CHANGED',
    actor: 'operator-ken',
    beforeState: { status: 'PENDING_PROCUREMENT' },
    afterState: { status: 'PROCUREMENT_CONFIRMED' },
    timestamp: '2026-07-13T11:22:00Z',
  },
  {
    id: 'aud-005',
    entityType: 'Approval',
    entityId: 'apr-002',
    action: 'APPROVAL_CREATED',
    actor: 'agent:canning',
    afterState: { approvalType: 'FACILITY_BOOKING', status: 'PENDING' },
    timestamp: '2026-07-13T11:30:00Z',
  },
  {
    id: 'aud-006',
    entityType: 'Approval',
    entityId: 'apr-002',
    action: 'APPROVAL_RESOLVED',
    actor: 'operator-ken',
    beforeState: { status: 'PENDING' },
    afterState: { status: 'APPROVED' },
    timestamp: '2026-07-13T12:05:00Z',
  },
  {
    id: 'aud-007',
    entityType: 'SurplusLot',
    entityId: 'lot-004',
    action: 'STATUS_CHANGED',
    actor: 'operator-ken',
    beforeState: { status: 'PROCUREMENT_CONFIRMED' },
    afterState: { status: 'IN_PRODUCTION' },
    timestamp: '2026-07-13T12:05:00Z',
  },
  {
    id: 'aud-008',
    entityType: 'Shipment',
    entityId: 'shp-001',
    action: 'SHIPMENT_CREATED',
    actor: 'agent:route',
    afterState: { status: 'CONFIRMED', foodBankId: 'fb-001', cansProduced: 5702 },
    timestamp: '2026-07-13T12:10:00Z',
  },
];

// ── Legacy mock surplus feed (kept for backward compat with existing UI) ───────
export const MOCK_SURPLUS_EVENTS = SURPLUS_LOTS.map(lot => ({
  id: lot.id,
  fisheryId: lot.supplierId,
  species: lot.species,
  lbs: lot.weightLbs,
  landingAt: SUPPLIERS.find(s => s.id === lot.supplierId)?.location ?? 'Unknown',
  landingDate: lot.harvestDate,
  marketPricePerLb: lot.marketPricePerLb,
  proposedDiscountPct: lot.proposedDiscountPct,
}));
